name: Application Build
on:
  workflow_run:
    workflows:
      - Backend Go Test
  workflow_dispatch:

jobs:
  backend-binary-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.20.6'
      - run: go build -o app
        working-directory: backend
      - uses: actions/upload-artifact@master
        with:
          name: backend-binary
          path: ./backend/app

  backend-docker-build:
    runs-on: ubuntu-latest
    needs: backend-binary-build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@master
        with:
          name: backend-binary
          path: ./backend/app
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/japp:latest



