name: Application Build
on:
  push:
    branches:
      - main
      - development
      - feature/*
  pull_request_target:
    branches:
      - main
      - development
jobs:
  backend-binary-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.20.6'
      - run: go build -o app
      - uses: actions/upload-artifact@master
        with:
          name: backend-binary
          path: ./app
  backend-docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        with:
          name: backend-binary
          path: ./app
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/japp:latest



