name: "Database/Flyway"

concurrency: data-sql-${{ github.ref }}

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/data-workflow.yaml
      - database/**

  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/data-workflow.yaml
      - database/**

jobs:
  sandbox_test:
    runs-on: ubuntu-latest
    env:
      MARIADB_USER: "sandbox"
      MARIADB_PASSWORD: "sandbox"
      MARIADB_DATABASE: "sandbox"
    steps:
      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop # Shutdown the Default MySQL, "sudo" is necessary, please not remove it

      - uses: getong/mariadb-action@v1.1
        with:
          host port: 3800
          container port: 3307
          mariadb version: '10.6'
          mysql database: $MARIADB_DATABASE
          mysql root password: $MARIADB_PASSWORD
          mysql user: $MARIADB_USER
          mysql password: $MARIADB_PASSWORD
      - name: "Checkout"
        uses: actions/checkout@v3
      
      - name: "Install Flyway"
        run: |
          wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/8.5.13/flyway-commandline-8.5.13-linux-x64.tar.gz | tar xvz && sudo ln -s `pwd`/flyway-8.5.13/flyway /usr/local/bin 
      
      - name: "Flyway Check"
        working-directory: database
        run: |
          flyway validate \
            -url=jdbc:mysql://localhost:3307/$MARIADB_DATABASE \
            -user=$MARIADB_USER \
            -password=$MARIADB_PASSWORD